// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9p0DbS_LxP83TPZebHi4YI7B3k48HHBg',
    appId: '1:79138049271:web:025a6f4f634a28547c17f2',
    messagingSenderId: '79138049271',
    projectId: 'pose-estimation-app-dd06c',
    authDomain: 'pose-estimation-app-dd06c.firebaseapp.com',
    storageBucket: 'pose-estimation-app-dd06c.firebasestorage.app',
    measurementId: 'G-5ND4W18GKZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB40YjLdkRzZiLAHv-LBvja_Ise_7QD7QA',
    appId: '1:79138049271:android:61d948d665af1eff7c17f2',
    messagingSenderId: '79138049271',
    projectId: 'pose-estimation-app-dd06c',
    storageBucket: 'pose-estimation-app-dd06c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAr-XA8R3gNRDs0u9Cn2Qn6YPBSZ9xcwA0',
    appId: '1:79138049271:ios:9505d518e1e159b67c17f2',
    messagingSenderId: '79138049271',
    projectId: 'pose-estimation-app-dd06c',
    storageBucket: 'pose-estimation-app-dd06c.firebasestorage.app',
    iosBundleId: 'com.bekir.poseEstimationApp',
  );

}